version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/output:/app/output
      - ./backend/logs:/app/logs
      - ./backend/.paddleocr:/root/.paddleocr
    env_file:
      - ./backend/.env
    # We don't mount 'input' here because the frontend will send the file directly over the API
